# Rates
PSII_recombination_v = recombination_with_pH_effects(k_recomb, QAm, Dy, pHlumen, fraction_pH_effect) # sindlgetO2: 1, QAm: -1, QA: 1, 
PSII_charge_separations = PSII_antenna_size*light_per_L * Phi2
v_QA = QAm * PQ * kQA
v_NDH = calc_v_NDH(Em_Fd, Em7_PQH2, pHstroma, pmf, k_NDH, Fd_red, Fd_ox, PQ, PQH2)
v_eqQAPQ = PQH2*QA*kQA/Keq_QA_PQ
PSI_charge_separations = P700_red * light_per_L * PSI_antenna_size * Fd_ox
v_PCoxidiation = PC_red * k_PC_to_P700 * P700_ox
v_PGR = calc_v_PGR(PGR_vmax, Fd_red, PQ, PQH2)
v_b6f = calc_v_b6f(max_b6f, b6f_content, pHlumen, pKreg, PQ, PQH2, PC_ox, PC_red, Em7_PC, Em7_PQH2, pmf)
v_Fd_NADP = k_Fd_to_NADP*Fd_red*NADP_pool
V_me = 4*0.000265*Fd_red/(Fd_red+Fd_ox)
v_Fdred = k_Fd_to_NADP*NADP_pool*Fd_red
NADPH_CBC = k_CBC*(1.0-np.exp(-t/600))*(np.log(NADPH_pool/NADP_pool)-np.log(1.25))/(np.log(3.5/1.25))
v_KEA = k_KEA*(Hlumen*Kstroma -  Hstroma*Klumen)*f_actvt
v_K_channel = perm_K * K_deltaG*(Klumen+Kstroma)/2
v_VCCN1 = k_VCCN1 * Cl_flux_relative(driving_force_Cl) * (Cl_stroma + Cl_lumen)/2
v_CLCE =  k_CLCE*(driving_force_Cl*2+pmf)*(Cl_stroma + Cl_lumen)*(Hlumen+Hstroma)/4
v_ZE = Z*kZE # changed
v_VE = V* VDE_max_turnover_number*pHmod # changed

# ODEs
dsingletO2=PSII_recombination_v*triplet_yield*triplet_to_singletO2_yield # singletO2
dQAm = PSII_charge_separations  + v_eqQAPQ  - v_QA - PSII_recombination_v # QAm
dQA = - PSII_charge_separations - v_eqQAPQ + v_QA + PSII_recombination_v # QA
dPQH2 = 0.5 * v_QA + 0.5 * v_NDH + 0.5 * v_PGR - 0.5 * v_b6f - 0.5 * v_eqQAPQ # n.pq_red()
dPQ = -0.5 * v_QA - 0.5 * v_NDH - 0.5 * v_PGR + 0.5 * v_b6f - 0.5 * v_eqQAPQ # n.pq_ox()
d_P700_ox = PSI_charge_separations - v_PCoxidiation # n.a0()
d_P700_red = - PSI_charge_separations + v_PCoxidiation # n.a1()
d_PC_ox = v_PCoxidiation - v_b6f # n.pc_ox()
d_PC_red = - v_PCoxidiation + v_b6f # n.pc_red()
dFd_red=PSI_charge_separations - v_Fd_NADP - v_NDH - v_PGR - V_me # n.fd_red()
dFd_ox=- PSI_charge_separations + v_Fd_NADP + v_NDH + v_PGR + V_me # n.fd_ox()
d_protons_to_ATP = Vproton_pmf_actvt(pmf, activity, ATP_synthase_max_turnover, n)
d_H_ATP_or_passive = V_H_light(light_per_L, d_protons_to_ATP, pmf, Hlumen)
d_ATP_made=d_protons_to_ATP/n 
dNADPH_pool=0.5 * v_Fdred - NADPH_CBC # n.nadph()
dNADP_pool= -0.5 * v_Fdred + NADPH_CBC # n.nadp()
dLEF= v_Fdred 
d_ATP_consumed = d_protons_to_ATP/n
d_protons_from_PSII = PSII_charge_separations - PSII_recombination_v
d_protons_from_b6f = v_b6f*2
dKlumen = v_KEA - v_K_channel * lumen_protons_per_turnover
dKstroma=0
dCl_lumen = v_VCCN1 + 2*v_CLCE * lumen_protons_per_turnover
dCl_stroma = -0.1* (v_VCCN1 + 2*v_CLCE * lumen_protons_per_turnover)
dHin = (PSII_charge_separations - PSII_recombination_v + v_b6f*2 + 2 * v_NDH - d_H_ATP_or_passive - v_KEA - v_CLCE)*lumen_protons_per_turnover
dpHlumen= -1*((PSII_charge_separations - PSII_recombination_v + v_b6f*2 + 2 * v_NDH - d_H_ATP_or_passive - v_KEA - v_CLCE)*lumen_protons_per_turnover) / buffering_capacity
dDy= PSII_charge_separations - PSII_recombination_v + PSI_charge_separations + v_b6f + 2 * v_NDH - v_K_channel - d_H_ATP_or_passive - v_VCCN1- 3*v_CLCE*Volts_per_charge
dpmf= 0.06* (-1*((PSII_charge_separations - PSII_recombination_v + v_b6f*2 + 2 * v_NDH - d_H_ATP_or_passive - v_KEA - v_CLCE)*lumen_protons_per_turnover) / buffering_capacity) + PSII_charge_separations - PSII_recombination_v + PSI_charge_separations + v_b6f + 2 * v_NDH - v_K_channel - d_H_ATP_or_passive - v_VCCN1- 3*v_CLCE*Volts_per_charge
dZ = v_VE - v_ZE
dV = v_ZE - v_VE
dNPQ=new_NPQ-NPQ 